
; ----------------------------------------- Media

[TrackInfo]
MeasureName=Artist
InlineSetting =Face  | #Font#
FontColor= 254, 240, 216
InlineSetting2=Weight| 600
InlineSetting5=CharacterSpacing | 0.7 | 0.7 |
StringEffect=Border
FontEffectColor= 19, 39, 64
StringAlign=CenterCenter
SolidColor =0,0,0,0
ClipString =1
AntiAlias  =1
X   =550
W   =150

[TrackInfo2]
MeasureName=Track
InlineSetting =Face  | #Font#
InlineSetting2=Size  | 18
InlineSetting3=Color | #Color#
InlineSetting3=Weight| 600
InlineSetting4=CharacterSpacing | 1 | 1 |
StringEffect=Border
FontEffectColor= 43, 42, 39
StringAlign=CenterCenter
SolidColor =0,0,0,0
ClipString =1
AntiAlias  =1
X   =280
Y   =175
W   =650



