[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed0], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed1], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed2], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed3], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed4], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed5], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed6], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed7], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed8], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed9], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed10], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=56R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed11], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed12], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed13], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed14], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed15], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed16], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed17], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed18], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed19], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed20], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed21], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed22], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar23]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed23], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar24]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed24], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar25]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed25], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar26]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed26], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar27]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed27], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar28]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed28], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar29]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed29], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar30]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed30], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar31]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed31], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar32]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed32], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar33]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed33], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0
[MeterBar34]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=0
Shape=Rectangle 0,0,(22*1),(90-(22*1))*[MeasureAudioSmoothed34], 1 | Fill Color #Color# | StrokeWidth 1 | StrokeColor 48, 48, 48, 255
DynamicVariables=1
TransformationMatrix=0.857167;0.515038;-3;0.857167;0;0