[DateStyle]
InlineSetting=Face | #Font#
InlineSetting2=Size | (41*[#Scale])
InlineSetting3=Color | #Color#
InlineSetting4=Weight | 600
InlineSetting5=CharacterSpacing | (7*[#Scale]) | (7*[#Scale])
StringEffect=Border
StringAlign=CenterTop

Y=(-10*[#Scale])

AntiAlias=1
DynamicVariables=1

TransformationMatrix=0.882948;0.46947;-0.46947;0.882948;0;0

[DateStyle2]
InlineSetting=Face | #Font#
InlineSetting2=Size | (42*[#Scale])
InlineSetting3=Color | #Color#
InlineSetting4=Weight | 600
InlineSetting5=CharacterSpacing | (7*[#Scale]) | (7*[#Scale])
StringEffect=Border
StringAlign=CenterTop

Y=(-11*[#Scale])

AntiAlias=1
DynamicVariables=1

TransformationMatrix=0.882948;0.46947;-0.46947;0.882948;0;0

