
; ----------------------------------------- Media

[TrackInfo]
MeasureName=Artist
InlineSetting =Face  | #Font#
FontColor= 254, 240, 216
InlineSetting2=Weight | 600
InlineSetting5=CharacterSpacing | (0.7*[#Scale]) | (0.7*[#Scale]) |
StringEffect=Border
FontEffectColor= 19, 39, 64
StringAlign=CenterCenter
SolidColor =0,0,0,0
ClipString =1
AntiAlias  =1
X   =(550*[#Scale])
W   =(150*[#Scale])

[TrackInfo2]
MeasureName=Track
InlineSetting =Face  | #Font#
InlineSetting2=Size  | (18*[#Scale])
InlineSetting3=Color | #Color#
InlineSetting3=Weight| 600
InlineSetting4=CharacterSpacing | (1*[#Scale]) | (1*[#Scale]) |
StringEffect=Border
FontEffectColor= 43, 42, 39
StringAlign=CenterCenter
SolidColor =0,0,0,0
ClipString =1
AntiAlias  =1
X   =(280*[#Scale])
Y   =(175*[#Scale])
W   =(650*[#Scale])



